import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	screen: {
		flex: 1,
		backgroundColor: '#F4F7FA',
	},
	contentContainer: {
		flexGrow: 1,
		paddingBottom: 100,
	},
	container: {
		width: '100%',
		minHeight: 320,
		backgroundColor: '#2C3E50',
		borderEndStartRadius: 40,
		borderEndEndRadius: 40,
		paddingBottom: 28,
		alignItems: 'center',
	},
	header: {
		position: 'absolute',
		top: 60,
		left: 0,
		right: 0,
		paddingHorizontal: 20,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		zIndex: 10,
	},
	areaIcones: {
		flexDirection: 'row',
		alignItems: 'center',
	},

	iconeBotao: {
		marginLeft: 14,
	},

	dropdownContainer: {
		position: 'absolute',
		top: 20,
		right: 10,
		zIndex: 999,
	},
	voltar: {
		flexDirection: 'row',
		alignItems: 'center',
	},
	textoVoltar: {
		color: 'white',
		fontSize: 18,
		fontWeight: 'bold',
	},
	cardsResumo: {
		width: '100%',
		paddingHorizontal: 20,
		marginTop: 120,
		flexDirection: 'row',
		justifyContent: 'space-between',
		gap: 12,
	},
	cardResumo: {
		flex: 1,
		minHeight: 150,
		backgroundColor: 'white',
		borderRadius: 24,
		paddingVertical: 20,
		paddingHorizontal: 14,
		alignItems: 'center',
		justifyContent: 'center',
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 10 },
		shadowOpacity: 0.18,
		shadowRadius: 10,
		elevation: 8,
	},
	iconeResumo: {
		width: 48,
		height: 48,
		borderRadius: 24,
		alignItems: 'center',
		justifyContent: 'center',
		marginBottom: 12,
	},
	iconeEntrada: {
		backgroundColor: '#2ecc7080',
	},
	iconeSaida: {
		backgroundColor: '#e74d3c77',
	},
	tituloResumo: {
		fontSize: 18,
		fontWeight: '700',
		color: '#34495E',
		marginBottom: 10,
		textAlign: 'center',
	},
	valorResumo: {
		fontSize: 18,
		fontWeight: '700',
		textAlign: 'center',
	},
	valorEntrada: {
		color: '#00C853',
	},
	valorSaida: {
		color: '#E74C3C',
	},
	filtroCard: {
		width: '90%',
		alignSelf: 'center',
		backgroundColor: 'white',
		borderRadius: 24,
		marginTop: 28,
		padding: 18,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 10 },
		shadowOpacity: 0.18,
		shadowRadius: 12,
		elevation: 10,
		zIndex: 2,
	},
	buscaArea: {
		width: '100%',
		height: 38,
		borderRadius: 12,
		backgroundColor: '#EDF2F4',
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 12,
		gap: 8,
	},
	inputBusca: {
		flex: 1,
		fontSize: 15,
		color: '#334155',
		paddingVertical: 0,
	},
	filtrosTipo: {
		marginTop: 16,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 10,
	},
	botaoTipo: {
		flex: 1,
		minHeight: 36,
		borderRadius: 10,
		borderWidth: 1,
		borderColor: '#E2E8F0',
		backgroundColor: '#FFFFFF',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 6,
	},
	botaoTipoAtivo: {
		backgroundColor: '#EEF2F7',
		borderColor: '#CBD5E1',
	},
	botaoTipoAtivoGanhos: {
		backgroundColor: '#2ECC71',
		borderColor: '#2ECC71',
	},
	botaoTipoAtivoGastos: {
		backgroundColor: '#E74C3C',
		borderColor: '#E74C3C',
	},
	textoBotaoTipo: {
		fontSize: 14,
		fontWeight: '700',
		color: '#334155',
	},
	textoBotaoTipoAtivo: {
		color: '#FFFFFF',
	},
	tituloSecao: {
		marginTop: 14,
		fontSize: 15,
		color: '#34495E',
		fontWeight: '700',
	},
	areaCategoria: {
		marginTop: 8,
		alignSelf: 'flex-start',
		position: 'relative',
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	botaoCategoria: {
		minWidth: 92,
		minHeight: 24,
		paddingHorizontal: 10,
		borderRadius: 6,
		backgroundColor: '#EEF2F7',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 8,
	},
	textoCategoriaBotao: {
		fontSize: 13,
		color: '#64748B',
		fontWeight: '700',
	},
	botaoLimparCategoria: {
		width: 24,
		height: 24,
		borderRadius: 12,
		backgroundColor: '#EEF2F7',
		alignItems: 'center',
		justifyContent: 'center',
	},
	listaCategorias: {
		position: 'absolute',
		top: 28,
		left: 0,
		minWidth: 120,
		backgroundColor: '#EEF2F7',
		borderRadius: 10,
		paddingVertical: 6,
		paddingHorizontal: 6,
		zIndex: 20,
		elevation: 8,
	},
	itemCategoria: {
		paddingVertical: 6,
		paddingHorizontal: 8,
	},
	textoItemCategoria: {
		fontSize: 13,
		color: '#334155',
	},
	areaPeriodo: {
		marginTop: 10,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 10,
	},
	inputPeriodo: {
		flex: 1,
		height: 36,
		borderRadius: 10,
		backgroundColor: '#EEF2F7',
		paddingHorizontal: 12,
		fontSize: 14,
		color: '#64748B',
		fontWeight: '700',
		textAlign: 'center',
	},
	textoEntrePeriodo: {
		fontSize: 14,
		color: '#334155',
		fontWeight: '700',
	},
	listaCard: {
		width: '90%',
		alignSelf: 'center',
		backgroundColor: 'white',
		borderRadius: 24,
		marginTop: 18,
		paddingVertical: 12,
		paddingHorizontal: 16,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 10 },
		shadowOpacity: 0.18,
		shadowRadius: 12,
		elevation: 10,
	},
	cabecalhoResultados: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginBottom: 12,
		paddingBottom: 12,
		borderBottomWidth: 1,
		borderBottomColor: '#EEF2F7',
	},
	tituloResultados: {
		fontSize: 16,
		fontWeight: '700',
		color: '#2C3E50',
		flex: 1,
	},
	areaIconesOrdenacao: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	botaoIcone: {
		width: 28,
		height: 28,
		borderRadius: 0,
		backgroundColor: 'transparent',
		alignItems: 'center',
		justifyContent: 'center',
	},
	botaoIconeAtivo: {
		opacity: 1,
	},
	listaResultados: {
		flexDirection: 'column',
		gap: 12,
	},
	itemResultado: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 5,
		paddingVertical: 8,
	},
	iconeItemResultado: {
		width: 40,
		height: 40,
		borderRadius: 20,
		alignItems: 'center',
		justifyContent: 'center',
	},
	textoNomeResultado: {
		flex: 1,
		fontSize: 14,
		color: '#2C3E50',
		fontWeight: '700',
		textAlign: 'center'
	},
	textoValorResultado: {
		fontSize: 14,
		fontWeight: '700',
		minWidth: 90,
		textAlign: 'right',
	},
	textoDataResultado: {
		fontSize: 10,
		color: '#94A3B8',
		fontWeight: '700',
		minWidth: 90,
		textAlign: 'right',
	},
	containerNomeCategoria: {
		flexDirection: 'column',
		gap: 5,
		alignItems: 'center',
		flex: 1,
	},
	categoriaResultado: {
		backgroundColor: '#EEF2F7',
		paddingHorizontal: 8,
		paddingVertical: 4,
		borderRadius: 6,
	},
	textoCategoriaResultado: {
		fontSize: 12,
		color: '#64748B',
		fontWeight: '600',
	},
	center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: 300,
  },
});
